{% set name = "opentelemetry-instrumentation-urllib" %}
{% set version = "0.27b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-urllib-{{ version }}.tar.gz
  sha256: b679809ff88efba667c3fc297465d3e26eca2c0be971110403839892a9126718

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.27b0
    - opentelemetry-semantic-conventions ==0.27b0
    - opentelemetry-util-http ==0.27b0
    - python >=3.6
    # - opentelemetry-test ==0.24b0
    # - httpretty ~=1.0
    # - opentelemetry-test-utils ==0.26b1
    # - httpretty ~=1.0
    # - opentelemetry-test-utils ==0.27b0
    # - httpretty ~=1.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-urllib
  summary: OpenTelemetry urllib instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
